config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [ :index, :destroy ]
  resources :positions
  resources :departments
  resources :employees
  resources :addresses
  root "employees#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :department # Relação com departamentos
  has_many :employees # Relação com funcionários

  before_destroy :set_default_position # Antes do cargo ser apagado é chamada função para setar cargo padrão ("Sem Cargo") para funcionários que tinham o cargo.

  private
  def set_default_position # Função que busca o cargo padrão e associa ao funcionário que possuia o cargo sendo removido.
    default_position = Position.find_by(name: "Sem Cargo")
    Employee.where(positions_id: self.id).update_all(positions_id: default_position.id)
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  layout "admin"
  before_action :set_position, only: %i[ show edit update destroy ]

  # GET /positions or /positions.json
  def index
    @positions = Position.all
  end

  # GET /positions/1 or /positions/1.json
  def show
  end

  # GET /positions/new
  def new
    @position = Position.new
    @departments = Department.all
  end

  # GET /positions/1/edit
  def edit
    @departments = Department.all
  end

  # POST /positions or /positions.json
  def create
    @position = Position.new(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to positions_url, notice: "Cargo foi criado com sucesso." }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1 or /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to positions_url, notice: "Cargo foi atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1 or /positions/1.json
  def destroy
    @position.destroy!

    respond_to do |format|
      format.html { redirect_to positions_url, notice: "Cargo foi deletado com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def position_params
      params.require(:position).permit(:name, :description, :department_id, :level, :base_salary, :requirements, :benefits, :status)
    end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<%= form_with(model: position, html: {class: 'form-horizontal'}) do |form| %>
  <% if position.errors.any? %>
    <div class="alert alert-danger">
      <p><%= pluralize(position.errors.count, "erro impediu", "erros impediram") %> que o cargo fosse cadastrado:</p>

      <ul>
        <% position.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= form.text_field :name, class: 'form-control', placeholder: 'Unidade de Mossoró' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :description, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= form.text_area :description, class: 'form-control', placeholder: 'Unidade de Mossoró' %>
    </div>
  </div>

  <div class="form-group">
      <%= form.label :department_id, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <% if @departments.nil? %>
        <%= select_tag "positions[department_id]", options_for_select(['Não há departamentos para selecionar']), disabled:true, class: 'form-control' %>
      <% else %>
        <%= form.collection_select :department_id, @departments, :id, :name, {}, { class: 'form-control' } %>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :level, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= select_tag "position[level]", options_for_select([['Junior', 'Junior'], ['Pleno', 'Pleno'], ['Senior', 'Senior'], ['Não se aplica', 'Não se aplica']], 'Junior'), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :base_salary, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= form.text_field :base_salary, class: 'form-control', placeholder: '1424.00' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :requirements, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= form.text_area :requirements, class: 'form-control', placeholder: 'Conhecimento básico de programação em ruby' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :benefits, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= form.text_area :benefits, class: 'form-control', placeholder: 'Auxílio transporte, plano de saúde...' %>
    </div>
  </div>

  <div class="form-group">
      <%= form.label :status, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= select_tag "position[status]", options_for_select([['Ativo', 'Ativo'], ['Inativo', 'Inativo']], 'Ativo'), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= form.submit class: 'btn btn-primary' %>
      <%= link_to 'Cancelar', positions_path, class: 'btn btn-default' %>
    </div>
<% end %>

app/views/positions/_position.html.erb
<div id="<%= dom_id position %>">
  <p>
    <strong>Name:</strong>
    <%= position.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= position.description %>
  </p>

  <p>
    <strong>Department:</strong>
    <%= position.department_id %>
  </p>

  <p>
    <strong>Level:</strong>
    <%= position.level %>
  </p>

  <p>
    <strong>Base salary:</strong>
    <%= position.base_salary %>
  </p>

  <p>
    <strong>Requirements:</strong>
    <%= position.requirements %>
  </p>

  <p>
    <strong>Benefits:</strong>
    <%= position.benefits %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= position.status %>
  </p>

</div>

app/views/positions/edit.html.erb
<% content_for :title, "Editing position" %>

<h1>Editar cargo</h1>

<%= render "form", position: @position %>

app/views/positions/index.html.erb
<% if (n = notice).present? %><p class="alert alert-warning"><%= n %></p><% end %>

<h1>
  Cargos

  &nbsp;
  <%= link_to new_position_path, class: 'btn btn-sm btn-default' do %>
    <i class="fa fa-plus"></i> Adicionar
  <% end %>
</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Cargo</th>
      <th>Descrição</th>
      <th>Departamento</th>
      <th>Nível</th>
      <th>Salário Base</th>
      <th>Requisitos</th>
      <th>Benefícios</th>
      <th>Status</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @positions.each do |position| %>
      <!-- Verificar se o usuário tem acesso ao departamento do cargo ou se ele é admin -->
      <% if current_user.admin? || current_user.departments.include?(position.department) %>
        <% unless position.name == "Sem Cargo" %>
          <tr>
            <td><%= position.name %></td>
            <td><%= position.description %></td>
            <td><%= position.department.name %></td>
            <td><%= position.level %></td>
            <td><%= number_to_currency position.base_salary %></td>
            <td><%= position.requirements %></td>
            <td><%= position.benefits %></td>
            <td><%= position.status %></td>
            <td nowrap>
              <%= link_to position, class: 'inline-form' do %>
                <button class="btn btn-sm btn-info" type="submit">
                  <i class="fa fa-eye"></i> Visualizar
                </button>
              <% end %>
              <%= link_to edit_position_path(position), class: 'inline-form' do %>
                <button class="btn btn-sm btn-primary" type="submit">
                  <i class="fa fa-edit"></i> Editar
                </button>
              <% end %>
              <%= form_with model: position, method: :delete, data: { turbo_confirm: 'Você tem certeza de que deseja remover este cargo?' }, class: 'inline-form delete-form' do %>
                <button class="btn btn-sm btn-danger" type="submit">
                  <i class="fa fa-trash"></i> Remover
                </button>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/positions/new.html.erb
<% content_for :title, "New position" %>

<h1>New position</h1>

<%= render "form", position: @position %>

app/views/positions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @position %>

<div>
  <%= link_to "Edit this position", edit_position_path(@position) %> |
  <%= link_to "Back to positions", positions_path %>

  <%= button_to "Destroy this position", @position, method: :delete %>
</div>