config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [ :index, :destroy ]
  resources :positions
  resources :departments
  resources :employees
  resources :addresses
  root "employees#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :positions # Relação com a tabela de cargos
  has_many :user_departments # Relação com a tabela de associação em si
  has_many :users, through: :user_departments # Relação de Departamento com usuários através da tabela de associação

  before_destroy :set_default_position_and_user_departments # Função é chamada antes da exclusão do departamento em questão

  private

  # Função utilizada apenas dentro do modelo de Departamento que associa o departamento padrão aos cargos e à tabela de associação
  # usuários e departamentos, antes da exclusão de um departamento.
  def set_default_position_and_user_departments
    # Associa o departamento padrão a default_department
    default_department = Department.find_by(name: "Sem Departamento")

    # Atualiza os cargos associados para o departamento padrão
    Position.where(department_id: self.id).update_all(department_id: default_department.id)

    # Para cada associação de usuário (na tabela user_departments), verifica se o usuário possui outros departamentos
    UserDepartment.where(department_id: self.id).find_each do |user_department|
      user = user_department.user
      if user.departments.count == 1
        # Se for o único departamento do usuário, é associado o departamento padrão a esse usuário.
        user_department.update(department_id: default_department.id)
      else
        # Caso contrário, apenas remove o departamento da associação em que estava.
        user_department.destroy
      end
    end
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  layout "admin"
  before_action :set_department, only: %i[ show edit update destroy ]

  # GET /departments or /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1 or /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments or /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to departments_url, notice: "Departamento foi criado com sucesso." }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1 or /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to departments_url, notice: "Departamento foi atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1 or /departments/1.json
  def destroy
    @department.destroy!

    respond_to do |format|
      format.html { redirect_to departments_url, notice: "Departamento foi apagado com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def department_params
      params.require(:department).permit(:code, :name, :description, :location, :status)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_department.html.erb
<div id="<%= dom_id department %>">
  <p>
    <strong>Code:</strong>
    <%= department.code %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= department.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= department.description %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= department.location %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= department.status %>
  </p>

</div>

app/views/departments/_form.html.erb
<%= form_with(model: department, html: {class: 'form-horizontal'}) do |form| %>
  <% if department.errors.any? %>
    <div class="alert alert-danger">
      <p><%= pluralize(department.errors.count, "erro impediu", "erros impediram") %> que o departamento fosse cadastrado:</p>

      <ul>
        <% department.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= form.label :code, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= form.text_field :code, class: 'form-control', placeholder: 'TI5' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= form.text_field :name, class: 'form-control', placeholder: 'Departamento de TI' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :description, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= form.text_area :description, class: 'form-control', placeholder: 'Esse departamento é legal...' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :location, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= form.text_field :location, class: 'form-control', placeholder: 'Unidade de Mossoró' %>
    </div>
  </div>

  <div class="form-group">
      <%= form.label :status, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= select_tag "department[status]", options_for_select([['Ativo', 'Ativo'], ['Inativo', 'Inativo']], 'Ativo'), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= form.submit class: 'btn btn-primary' %>
      <%= link_to 'Cancelar', departments_path, class: 'btn btn-default' %>
    </div>
<% end %>

app/views/departments/edit.html.erb
<% content_for :title, "Editing department" %>

<h1>Editar departamento</h1>

<%= render "form", department: @department %>

app/views/departments/index.html.erb
<% if (n = notice).present? %><p class="alert alert-warning"><%= n %></p><% end %>

<h1>
  Departamentos

  &nbsp;
  <%= link_to new_department_path, class: 'btn btn-sm btn-default' do %>
    <i class="fa fa-plus"></i> Adicionar
  <% end %>
</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Código</th>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Localização</th>
      <th>Status</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <!-- Verificar se o usuário tem acesso ao departamento ou se ele é admin -->
      <% if current_user.admin? || current_user.departments.include?(department) %>
        <% unless department.name == "Sem Departamento" %>
          <tr>
            <td><%= department.code %></td>
            <td><%= department.name %></td>
            <td><%= department.description %></td>
            <td><%= department.location %></td>
            <td><%= department.status %></td>
            <td nowrap>
              <%= link_to department, class: 'inline-form' do %>
                <button class="btn btn-sm btn-info" type="submit">
                  <i class="fa fa-eye"></i> Visualizar
                </button>
              <% end %>
              <%= link_to edit_department_path(department), class: 'inline-form' do %>
                <button class="btn btn-sm btn-primary" type="submit">
                  <i class="fa fa-edit"></i> Editar
                </button>
              <% end %>
              <%= form_with model: department, method: :delete, data: { turbo_confirm: 'Você tem certeza de que deseja remover este departamento?' }, class: 'inline-form delete-form' do %>
                <button class="btn btn-sm btn-danger" type="submit">
                  <i class="fa fa-trash"></i> Remover
                </button>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/departments/new.html.erb
<% content_for :title, "New department" %>

<h1>New department</h1>

<%= render "form", department: @department %>

app/views/departments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @department %>

<div>
  <%= link_to "Edit this department", edit_department_path(@department) %> |
  <%= link_to "Back to departments", departments_path %>

  <%= button_to "Destroy this department", @department, method: :delete %>
</div>